// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmgWI6oBLI__2jdx4RVopvnCuKJITv0OY',
    appId: '1:372490329151:web:8aace88d6bf657949b2c8a',
    messagingSenderId: '372490329151',
    projectId: 'tsn-store-fb',
    authDomain: 'tsn-store-fb.firebaseapp.com',
    storageBucket: 'tsn-store-fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAORxevz8MpZazkIzYTAu3K8PG_y0-ABnE',
    appId: '1:372490329151:android:6175ff9d6d1466529b2c8a',
    messagingSenderId: '372490329151',
    projectId: 'tsn-store-fb',
    storageBucket: 'tsn-store-fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3cZvON38X9QqLmVszF41GUifXTZx9Nl4',
    appId: '1:372490329151:ios:c2faf503b4570c759b2c8a',
    messagingSenderId: '372490329151',
    projectId: 'tsn-store-fb',
    storageBucket: 'tsn-store-fb.appspot.com',
    iosClientId: '372490329151-98pjcbhvp5mrfhab628j714s4e8gausk.apps.googleusercontent.com',
    iosBundleId: 'id.fansystem.tsnStore',
  );
}
